name: k8s-util
version: 0.0.0.1
description: Sample pods, deployments
synopsis: Kubernetes pods and deployments for deena
maintainer: dinkar.ganti@gmail.com
category: Kubernetes
license: AllRightsReserved

library:
  source-dirs : lib
  ghc-options : 
    - -Wall
    - -freverse-errors

executables:
  simple:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -freverse-errors

tests:
  k8s-util-tasty:
    source-dirs: tests
    main: Main.hs
    dependencies:
      - k8s-util
      - hedgehog
      - hedgehog-quickcheck
      - base
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-hspec

dependencies:
- base
- containers
- data-default
- http-client
- http-types
- iproute
- kubernetes-client
- kubernetes-client-core
- microlens
- safe-exceptions
- stm
- text